[theme]
primaryColor="#6C63FF"
backgroundColor="#D8BFD8"
secondaryBackgroundColor="#BDB5D5"
textColor="#000000"
font="sans serif"
headingFont  = "Zeyada:https://fonts.googleapis.com/css2?family=Zeyada&display=swap"
