[theme]
primaryColor="#6C63FF"
backgroundColor="#C9A9A6"
secondaryBackgroundColor="#AA336A"
textColor="#000000"
font="sans serif"
[theme.headingFontSizes]
font = "Zedaya:https://fonts.googleapis.com/css2?family=Zeyada&display=swap"
